### ISSUE TITLE
Messy Syntax in "Getting Started with Sass" Article

### ISSUE THREAD

**Issue by varjmes** [alistapart/AListApart#104]
Article in question: http://alistapart.com/article/getting-started-with-sass

A lot of the SCSS Syntax snippets in the article are messy. It seems to be a case of new lines being stripped out or something to that effect.

EG #snippet16 

``` scss

.container {
  @include clearfix;
  @include grid-unit(12);
  float: none;
  margin: 0 auto;
}.main-content {
  @include grid-unit(8);
}.sidebar {
  @include grid-unit(4);
  margin-right: 0;
}

```

Is tidier if it is like this:

``` scss

.container {
  @include clearfix;
  @include grid-unit(12);
  float: none;
  margin: 0 auto;
}

.main-content {
  @include grid-unit(8);
}

.sidebar {
  @include grid-unit(4);
  margin-right: 0;
}

```

If I'm wrong I apologise, I'm still learning so perhaps this is a way of writing syntax I have not come across. 

-- Charlotte
