### ISSUE TITLE
Misc `,` in CSS

### ISSUE THREAD

**Issue by michaelbragg** [alistapart/AListApart#25]
Misc `,` on [Line1947](https://github.com/alistapart/AListApart/blob/dev/site_assets/css/style.css#L1947).

``` css
.main-content > figure.quote > blockquote > p,,
.main-content > article.link-post > figure.quote > blockquote > p {
        margin-bottom: 18px;
}
```

Ideal for anybody who want to try out their first-ever pull requests.
